# Generated by Django 3.0.4 on 2020-06-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_enter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enter',
        ),
    ]
