# Generated by Django 3.0.4 on 2020-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_delete_enter'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='output',
            name='asin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='output',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='output',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='output',
            name='rank',
            field=models.CharField(max_length=200),
        ),
    ]
