# Generated by Django 3.0.4 on 2020-06-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_output_cpu'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='output',
            name='cpu',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
