# Generated by Django 3.0.4 on 2020-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200612_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='screen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
