# Generated by Django 3.0.4 on 2020-06-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_output_ram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='price',
            field=models.FloatField(max_length=200),
        ),
    ]
