# Generated by Django 3.0.4 on 2020-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200615_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='rank',
            field=models.IntegerField(blank=True),
        ),
    ]
