# Generated by Django 3.0.4 on 2020-06-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200615_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
