# Generated by Django 3.0.4 on 2020-06-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_output_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='DVD',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='List',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='keyboard',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='security',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='vc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
