# Generated by Django 3.0.4 on 2020-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_auto_20200615_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='office',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='upc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
